<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="ProgId" content="FrontPage.Editor.Document ">
<link rel="stylesheet" href="../inc/setstyle.css">
<title></title>
</head>
<body>
<table border="0" width="580" cellspacing="1" cellpadding="0" align="center">
  <tr>
    <td width="100%" class="FormName" colspan="2">各項表單查詢作業</td>
  </tr>
  <tr>
    <td width="100%" colspan="2">
      <hr noshade size="1" color="#000080">
    </td>
  </tr>
  <tr>
    <td class="Formtext" width="60%">【<%=taskLable%>】</td>
      <td class="FormLink" valign="top" width="40%" align="right">               
         <div align="center"><font size=2>處理類別:
           <select name=formselect size=1>
              <option value="" selected>請選擇</option>
		      <option value="PABDB01M">基本資料</option>
		      <option value="PABDB02M">現職資料</option>
	          <option value="PABDB03M">借調資料</option>
		      <option value="PABDB04M">兼職資料</option>
		      <option value="PABDB05M">學歷資料</option>
		      <option value="PABDB06M">考試資料</option>
	  	      <option value="PABDB07M">教師資格資資料</option>		
		      <option value="PABDB08M">檢覈資料</option>
		      <option value="PABDB10M">外國語文資料</option>
		      <option value="PABDB13M">訓練進訓</option>
		      <option value="PABDB16M">家屬資料</option>
		      <option value="PABDB19M">經歷資料</option>
		      <option value="PABDB20M">考績資料</option>
		      <option value="PABDB21M">獎懲資料</option>
		      <option value="PABDB22M">甄審資料</option>
		      <option value="PABDB34M">銓審資料</option>	
		      <option value="PABDB37M">請任免資料</option>
		      <option value="">進修資料</option>							
		   </select>
		</div>    
	 </td>
	 </td>	
  </tr>
  <tr>
    <td width="100%" colspan="2" class="FormRtext">所有欄位空白即可查詢全部資料 </td>
  </tr>     
    <tr>
      <td width="100%" colspan="2">
    <!-- 程式開始-->